import type { Project, ApartmentProject } from './types';

export const apartmentProjects: ApartmentProject[] = [
  {
    id: 1,
    src: [
      '/images/projects/br_1/2.jpg',
      '/images/projects/br_1/3.jpg',
      '/images/projects/br_1/4.jpg',
      '/images/projects/br_1/5.jpg',
      '/images/projects/br_1/6.jpg',
    ],
    title: 'apartmentProjects.items.bi_residence.title',
    description: 'apartmentProjects.items.bi_residence.description',
    option: 'apartmentProjects.items.bi_residence.option',
  },
  {
    id: 2,
    src: [
      '/images/projects/br_2/1.jpg',
      '/images/projects/br_2/2.jpg',
      '/images/projects/br_2/3.jpg',
      '/images/projects/br_2/4.jpg',
      '/images/projects/br_2/5.jpg',
      '/images/projects/br_2/6.jpg',
      '/images/projects/br_2/7.jpg',
      '/images/projects/br_2/8.jpg',
      '/images/projects/br_2/9.jpg',
      '/images/projects/br_2/10.jpg',
      '/images/projects/br_2/11.jpg',
    ],
    title: 'apartmentProjects.items.bagrationi.title',
    description: 'apartmentProjects.items.bagrationi.description',
    option: 'apartmentProjects.items.bagrationi.option',
  },
  {
    id: 3,
    src: [
      '/images/projects/pt/1.jpeg',
      '/images/projects/pt/2.jpeg',
      '/images/projects/pt/3.jpeg',
      '/images/projects/pt/4.jpeg',
      '/images/projects/pt/5.jpeg',
      '/images/projects/pt/6.jpeg',
      '/images/projects/pt/7.jpeg',
      '/images/projects/pt/8.jpeg',
      '/images/projects/pt/9.jpeg',
      '/images/projects/pt/10.jpeg',
      '/images/projects/pt/11.jpeg',
      '/images/projects/pt/12.jpeg',
      '/images/projects/pt/13.jpeg',
      '/images/projects/pt/14.jpeg',
      '/images/projects/pt/15.jpeg',
      '/images/projects/pt/16.jpeg',
      '/images/projects/pt/17.jpeg',
      '/images/projects/pt/18.jpeg',
      '/images/projects/pt/19.jpeg',
      '/images/projects/pt/20.jpeg',
      '/images/projects/pt/21.jpeg',
      '/images/projects/pt/22.jpeg',
      '/images/projects/pt/23.jpeg',
      '/images/projects/pt/24.jpeg',
      '/images/projects/pt/25.jpeg',
      '/images/projects/pt/26.jpeg',
      '/images/projects/pt/27.jpeg',
    ],
    title: 'apartmentProjects.items.porta_tower.title',
    description: 'apartmentProjects.items.porta_tower.description',
    option: 'apartmentProjects.items.porta_tower.option',
  },
];

export const projects: Project[] = [
  {
    id: 0,
    src: '/images/projects/pt/27.jpeg',
    category: 'projects',
  },
  {
    id: 1,
    src: '/images/projects/5.jpeg',
    category: 'wardrobes',
  },
  {
    id: 2,
    src: '/images/projects/6.jpg',
    category: 'kitchens',
  },
  {
    id: 3,
    src: '/images/projects/7.jpg',
    category: 'kitchens',
  },
  {
    id: 4,
    src: '/images/projects/8.jpeg',
    category: 'kitchens',
  },
  {
    id: 5,
    src: '/images/projects/10.jpeg',
    category: 'b2b',
  },
  {
    id: 6,
    src: '/images/projects/11.jpeg',
    category: 'wardrobes',
  },
  {
    id: 7,
    src: '/images/projects/12.jpeg',
    category: 'kitchens',
  },
  {
    id: 8,
    src: '/images/projects/13.jpeg',
    category: 'hallways',
  },
  {
    id: 9,
    src: '/images/projects/chakvi-tropical.jpeg',
    category: 'kitchens',
  },
  {
    id: 10,
    src: '/images/projects/chakvi-tropical-1.jpeg',
    category: 'kitchens',
  },
  {
    id: 11,
    src: '/images/projects/kobuleti.jpeg',
    category: 'kitchens',
  },
  {
    id: 12,
    src: '/images/projects/kobuleti-1.jpeg',
    category: 'kitchens',
  },
];
