import type { Project, ApartmentProject, ProjectCategoryData } from './types';

export const projectCategories = [
  {
    category: 'projects',
    items: [
      {
        id: 1,
        src: [
          '/images/projects/br_1/2.jpg',
          '/images/projects/br_1/3.jpg',
          '/images/projects/br_1/4.jpg',
          '/images/projects/br_1/5.jpg',
          '/images/projects/br_1/6.jpg',
        ],
        title: 'apartmentProjects.items.bi_residence.title',
        description: 'apartmentProjects.items.bi_residence.description',
        option: 'apartmentProjects.items.bi_residence.option',
      },
      {
        id: 2,
        src: [
          '/images/projects/br_2/1.jpg',
          '/images/projects/br_2/2.jpg',
          '/images/projects/br_2/3.jpg',
          '/images/projects/br_2/4.jpg',
          '/images/projects/br_2/5.jpg',
          '/images/projects/br_2/6.jpg',
          '/images/projects/br_2/7.jpg',
          '/images/projects/br_2/8.jpg',
          '/images/projects/br_2/9.jpg',
          '/images/projects/br_2/10.jpg',
          '/images/projects/br_2/11.jpg',
        ],
        title: 'apartmentProjects.items.bagrationi.title',
        description: 'apartmentProjects.items.bagrationi.description',
        option: 'apartmentProjects.items.bagrationi.option',
      },
      {
        id: 3,
        src: [
          '/images/projects/pt/1.jpeg',
          '/images/projects/pt/2.jpeg',
          '/images/projects/pt/3.jpeg',
          '/images/projects/pt/4.jpeg',
          '/images/projects/pt/5.jpeg',
          '/images/projects/pt/6.jpeg',
          '/images/projects/pt/7.jpeg',
          '/images/projects/pt/8.jpeg',
          '/images/projects/pt/9.jpeg',
          '/images/projects/pt/10.jpeg',
          '/images/projects/pt/11.jpeg',
          '/images/projects/pt/12.jpeg',
          '/images/projects/pt/13.jpeg',
          '/images/projects/pt/14.jpeg',
          '/images/projects/pt/15.jpeg',
          '/images/projects/pt/16.jpeg',
          '/images/projects/pt/17.jpeg',
          '/images/projects/pt/18.jpeg',
          '/images/projects/pt/19.jpeg',
          '/images/projects/pt/20.jpeg',
          '/images/projects/pt/21.jpeg',
          '/images/projects/pt/22.jpeg',
          '/images/projects/pt/23.jpeg',
          '/images/projects/pt/24.jpeg',
          '/images/projects/pt/25.jpeg',
          '/images/projects/pt/26.jpeg',
          '/images/projects/pt/27.jpeg',
        ],
        title: 'apartmentProjects.items.porta_tower.title',
        description: 'apartmentProjects.items.porta_tower.description',
        option: 'apartmentProjects.items.porta_tower.option',
      },
      {
        id: 4,
        src: [
          '/images/projects/single_contour/1.png',
          '/images/projects/single_contour/2.png',
          '/images/projects/single_contour/3.png',
          '/images/projects/single_contour/4.png',
          '/images/projects/single_contour/5.png',
          '/images/projects/single_contour/6.png',
          '/images/projects/single_contour/7.webp',
        ],
        title: 'apartmentProjects.items.single_contour.title',
        description: 'apartmentProjects.items.single_contour.description',
        option: 'apartmentProjects.items.single_contour.option',
      },
    ],
  },
  {
    category: 'kitchens',
    items: [
      {
        id: 1,
        src: [
          '/images/kitchens/country_house/1.jpg',
          '/images/kitchens/country_house/2.jpg',
          '/images/kitchens/country_house/3.jpg',
        ],
        title: 'kitchens.items.country_house.title',
        description: 'kitchens.items.country_house.description',
        option: 'kitchens.items.country_house.option',
      },
      {
        id: 2,
        src: [
          '/images/kitchens/white_geometry/1.jpg',
          '/images/kitchens/white_geometry/2.jpg',
          '/images/kitchens/white_geometry/3.jpg',
        ],
        title: 'kitchens.items.white_geometry.title',
        description: 'kitchens.items.white_geometry.description',
        option: 'kitchens.items.white_geometry.option',
      },
      {
        id: 3,
        src: [
          '/images/kitchens/kitchen_with_island/1.png',
          '/images/kitchens/kitchen_with_island/2.png',
          '/images/kitchens/kitchen_with_island/3.png',
        ],
        title: 'kitchens.items.kitchen_with_island.title',
        description: 'kitchens.items.kitchen_with_island.description',
        option: 'kitchens.items.kitchen_with_island.option',
      },
      {
        id: 4,
        src: [
          '/images/kitchens/integrated_kitchen/1.jpg',
          '/images/kitchens/integrated_kitchen/2.png',
          '/images/kitchens/integrated_kitchen/3.png',
          '/images/kitchens/integrated_kitchen/4.jpg',
        ],
        title: 'kitchens.items.integrated_kitchen.title',
        description: 'kitchens.items.integrated_kitchen.description',
        option: 'kitchens.items.integrated_kitchen.option',
      },
      {
        id: 5,
        src: [
          '/images/kitchens/green_wood/1.webp',
          '/images/kitchens/green_wood/2.webp',
          '/images/kitchens/green_wood/3.webp',
          '/images/kitchens/green_wood/4.webp',
          '/images/kitchens/green_wood/5.webp',
        ],
        title: 'kitchens.items.green_wood.title',
        description: 'kitchens.items.green_wood.description',
        option: 'kitchens.items.green_wood.option',
      },
      {
        id: 6,
        src: [
          '/images/kitchens/functional_minimalism/1.png',
          '/images/kitchens/functional_minimalism/2.png',
          '/images/kitchens/functional_minimalism/3.png',
        ],
        title: 'kitchens.items.functional_minimalism.title',
        description: 'kitchens.items.functional_minimalism.description',
        option: 'kitchens.items.functional_minimalism.option',
      },
      {
        id: 7,
        src: [
          '/images/kitchens/captains_family/1.png',
          '/images/kitchens/captains_family/2.png',
          '/images/kitchens/captains_family/3.png',
          '/images/kitchens/captains_family/4.png',
          '/images/kitchens/captains_family/5.png',
          '/images/kitchens/captains_family/6.png',
        ],
        title: 'kitchens.items.captains_family.title',
        description: 'kitchens.items.captains_family.description',
        option: 'kitchens.items.captains_family.option',
      },
      {
        id: 8,
        src: [
          '/images/kitchens/snow_white/1.png',
          '/images/kitchens/snow_white/2.png',
          '/images/kitchens/snow_white/3.png',
          '/images/kitchens/snow_white/4.png',
        ],
        title: 'kitchens.items.snow_white.title',
        description: 'kitchens.items.snow_white.description',
        option: 'kitchens.items.snow_white.option',
      },
    ],
  },
  {
    category: 'hallways',
    items: [
      {
        id: 1,
        src: ['/images/hallways/linea/1.jpg', '/images/hallways/linea/2.jpg'],
        title: 'hallways.items.linea.title',
        description: 'hallways.items.linea.description',
        option: 'hallways.items.linea.option',
      },
      {
        id: 2,
        src: [
          '/images/hallways/integrated_storage/1.png',
          '/images/hallways/integrated_storage/2.png',
          '/images/hallways/integrated_storage/3.png',
          '/images/hallways/integrated_storage/4.png',
        ],
        title: 'hallways.items.integrated_storage.title',
        description: 'hallways.items.integrated_storage.description',
        option: 'hallways.items.integrated_storage.option',
      },
      {
        id: 3,
        src: [
          '/images/hallways/contrasting_entryway/1.png',
          '/images/hallways/contrasting_entryway/2.png',
        ],
        title: 'hallways.items.contrasting_entryway.title',
        description: 'hallways.items.contrasting_entryway.description',
        option: 'hallways.items.contrasting_entryway.option',
      },
    ],
  },
  {
    category: 'bedrooms',
    items: [
      {
        id: 1,
        src: [
          '/images/bedrooms/la_quinta/1.jpg',
          '/images/bedrooms/la_quinta/2.png',
          '/images/bedrooms/la_quinta/3.jpg',
        ],
        title: 'bedrooms.items.LA_QUINTA.title',
        description: 'bedrooms.items.LA_QUINTA.description',
        option: 'bedrooms.items.LA_QUINTA.option',
      },
      {
        id: 2,
        src: [
          '/images/bedrooms/storage_systems_1/1.jpg',
          '/images/bedrooms/storage_systems_1/2.jpg',
          '/images/bedrooms/storage_systems_1/3.jpg',
          '/images/bedrooms/storage_systems_1/4.jpg',
          '/images/bedrooms/storage_systems_1/5.jpg',
        ],
        title: 'bedrooms.items.storage_systems_1.title',
        description: 'bedrooms.items.storage_systems_1.description',
        option: 'bedrooms.items.storage_systems_1.option',
      },
      {
        id: 3,
        src: [
          '/images/bedrooms/storage_systems_2/1.jpg',
          '/images/bedrooms/storage_systems_2/2.jpg',
          '/images/bedrooms/storage_systems_2/3.jpg',
          '/images/bedrooms/storage_systems_2/4.jpg',
          '/images/bedrooms/storage_systems_2/5.jpg',
        ],
        title: 'bedrooms.items.storage_systems_2.title',
        description: 'bedrooms.items.storage_systems_2.description',
        option: 'bedrooms.items.storage_systems_2.option',
      },
    ],
  },
  {
    category: 'children-rooms',
    items: [
      {
        id: 1,
        src: [
          '/images/children/helper_tower/tower.webp',
          '/images/children/helper_tower/tower_1.webp',
        ],
        title: 'children-rooms.items.helper_tower.title',
        description: 'children-rooms.items.helper_tower.description',
        option: 'children-rooms.items.helper_tower.option',
      },
      {
        id: 2,
        src: [
          '/images/children/growing_chair/1.webp',
          '/images/children/growing_chair/grow_1.webp',
        ],
        title: 'children-rooms.items.growing_chair.title',
        description: 'children-rooms.items.growing_chair.description',
        option: 'children-rooms.items.growing_chair.option',
      },
    ],
  },
  {
    category: 'bathrooms',
    items: [
      {
        id: 1,
        src: [
          '/images/bathrooms/warm_minimalism/warm.jpg',
          '/images/bathrooms/warm_minimalism/warm_1.jpg',
        ],
        title: 'bathrooms.items.warm_minimalism.title',
        description: 'bathrooms.items.warm_minimalism.description',
        option: 'bathrooms.items.warm_minimalism.option',
      },
      {
        id: 2,
        src: [
          '/images/bathrooms/gray_geometry/gray.jpg',
          '/images/bathrooms/gray_geometry/gray_1.jpg',
          '/images/bathrooms/gray_geometry/gray_2.jpg',
        ],
        title: 'bathrooms.items.gray_geometry.title',
        description: 'bathrooms.items.gray_geometry.description',
        option: 'bathrooms.items.gray_geometry.option',
      },
      {
        id: 3,
        src: [
          '/images/bathrooms/concrete_and_wood/wood.jpg',
          '/images/bathrooms/concrete_and_wood/wood_1.jpg',
          '/images/bathrooms/concrete_and_wood/wood_2.jpg',
          '/images/bathrooms/concrete_and_wood/wood_3.webp',
        ],
        title: 'bathrooms.items.concrete_and_wood.title',
        description: 'bathrooms.items.concrete_and_wood.description',
        option: 'bathrooms.items.concrete_and_wood.option',
      },
    ],
  },
  {
    category: 'wardrobes',
    items: [
      {
        id: 1,
        src: [
          '/images/wardrobes/with_ouvered_fronts/1.png',
          '/images/wardrobes/with_ouvered_fronts/2.png',
        ],
        title: 'wardrobes.items.with_ouvered_fronts.title',
        description: 'wardrobes.items.with_ouvered_fronts.description',
        option: 'wardrobes.items.with_ouvered_fronts.option',
      },
      {
        id: 2,
        src: [
          '/images/wardrobes/graphite_line/1.png',
          '/images/wardrobes/graphite_line/2.png',
          '/images/wardrobes/graphite_line/3.png',
          '/images/wardrobes/graphite_line/4.png',
        ],
        title: 'wardrobes.items.graphite_line.title',
        description: 'wardrobes.items.graphite_line.description',
        option: 'wardrobes.items.graphite_line.option',
      },
      {
        id: 3,
        src: [
          '/images/wardrobes/with_lighting/1.jpg',
          '/images/wardrobes/with_lighting/2.jpg',
          '/images/wardrobes/with_lighting/3.jpg',
        ],
        title: 'wardrobes.items.with_lighting.title',
        description: 'wardrobes.items.with_lighting.description',
        option: 'wardrobes.items.with_lighting.option',
      },
      {
        id: 4,
        src: [
          '/images/wardrobes/wooden_wardrobe/1.png',
          '/images/wardrobes/wooden_wardrobe/2.png',
          '/images/wardrobes/wooden_wardrobe/3.png',
        ],
        title: 'wardrobes.items.wooden_wardrobe.title',
        description: 'wardrobes.items.wooden_wardrobe.description',
        option: 'wardrobes.items.wooden_wardrobe.option',
      },
    ],
  },

  {
    category: 'b2b',
    items: [
      {
        id: 1,
        src: [
          '/images/b2b/kindergarten_space/active_space_1.jpg',
          '/images/b2b/kindergarten_space/active_space_2.jpg',
          '/images/b2b/kindergarten_space/active_space_3.jpg',
          '/images/b2b/kindergarten_space/active_space_4.jpg',
        ],
        title: 'b2b.items.kindergarten_space.title',
        description: 'b2b.items.kindergarten_space.description',
        option: 'b2b.items.kindergarten_space.option',
      },
      {
        id: 2,
        src: [
          '/images/b2b/organic_shop/organic.webp',
          '/images/b2b/organic_shop/organic_1.webp',
          '/images/b2b/organic_shop/organic_2.webp',
        ],
        title: 'b2b.items.organic_shop.title',
        description: 'b2b.items.organic_shop.description',
        option: 'b2b.items.organic_shop.option',
      },
    ],
  },
  {
    category: 'others',
    items: [
      {
        id: 1,
        src: [
          '/images/others/1.jpg',
          '/images/others/2.jpg',
          '/images/others/3.jpg',
          '/images/others/4.jpg',
          '/images/others/5.jpg',
          '/images/others/6.jpg',
          '/images/others/7.jpg',
          '/images/others/8.jpg',
          '/images/others/9.png',
          '/images/others/10.jpg',
          '/images/others/11.jpg',
          '/images/others/12.jpg',
          '/images/others/13.jpg',
          '/images/others/14.webp',
        ],
        title: 'others.items.others.title',
        description: 'others.items.others.description',
        option: 'others.items.others.option',
      },
    ],
  },
] satisfies ProjectCategoryData[];

export const apartmentProjects: ApartmentProject[] = [
  {
    id: 1,
    src: [
      '/images/projects/br_1/2.jpg',
      '/images/projects/br_1/3.jpg',
      '/images/projects/br_1/4.jpg',
      '/images/projects/br_1/5.jpg',
      '/images/projects/br_1/6.jpg',
    ],
    title: 'apartmentProjects.items.bi_residence.title',
    description: 'apartmentProjects.items.bi_residence.description',
    option: 'apartmentProjects.items.bi_residence.option',
  },
  {
    id: 2,
    src: [
      '/images/projects/br_2/1.jpg',
      '/images/projects/br_2/2.jpg',
      '/images/projects/br_2/3.jpg',
      '/images/projects/br_2/4.jpg',
      '/images/projects/br_2/5.jpg',
      '/images/projects/br_2/6.jpg',
      '/images/projects/br_2/7.jpg',
      '/images/projects/br_2/8.jpg',
      '/images/projects/br_2/9.jpg',
      '/images/projects/br_2/10.jpg',
      '/images/projects/br_2/11.jpg',
    ],
    title: 'apartmentProjects.items.bagrationi.title',
    description: 'apartmentProjects.items.bagrationi.description',
    option: 'apartmentProjects.items.bagrationi.option',
  },
  {
    id: 3,
    src: [
      '/images/projects/pt/1.jpeg',
      '/images/projects/pt/2.jpeg',
      '/images/projects/pt/3.jpeg',
      '/images/projects/pt/4.jpeg',
      '/images/projects/pt/5.jpeg',
      '/images/projects/pt/6.jpeg',
      '/images/projects/pt/7.jpeg',
      '/images/projects/pt/8.jpeg',
      '/images/projects/pt/9.jpeg',
      '/images/projects/pt/10.jpeg',
      '/images/projects/pt/11.jpeg',
      '/images/projects/pt/12.jpeg',
      '/images/projects/pt/13.jpeg',
      '/images/projects/pt/14.jpeg',
      '/images/projects/pt/15.jpeg',
      '/images/projects/pt/16.jpeg',
      '/images/projects/pt/17.jpeg',
      '/images/projects/pt/18.jpeg',
      '/images/projects/pt/19.jpeg',
      '/images/projects/pt/20.jpeg',
      '/images/projects/pt/21.jpeg',
      '/images/projects/pt/22.jpeg',
      '/images/projects/pt/23.jpeg',
      '/images/projects/pt/24.jpeg',
      '/images/projects/pt/25.jpeg',
      '/images/projects/pt/26.jpeg',
      '/images/projects/pt/27.jpeg',
    ],
    title: 'apartmentProjects.items.porta_tower.title',
    description: 'apartmentProjects.items.porta_tower.description',
    option: 'apartmentProjects.items.porta_tower.option',
  },
];

export const projects: Project[] = [
  {
    id: 0,
    src: '/images/projects/pt/27.jpeg',
    category: 'projects',
  },
  {
    id: 1,
    src: '/images/projects/5.jpeg',
    category: 'wardrobes',
  },
  {
    id: 2,
    src: '/images/projects/6.jpg',
    category: 'kitchens',
  },
  {
    id: 3,
    src: '/images/projects/7.jpg',
    category: 'kitchens',
  },
  {
    id: 4,
    src: '/images/projects/8.jpeg',
    category: 'kitchens',
  },
  {
    id: 5,
    src: '/images/projects/10.jpeg',
    category: 'b2b',
  },
  {
    id: 6,
    src: '/images/projects/11.jpeg',
    category: 'wardrobes',
  },
  {
    id: 7,
    src: '/images/projects/12.jpeg',
    category: 'kitchens',
  },
  {
    id: 8,
    src: '/images/projects/chakvi-tropical.jpeg',
    category: 'kitchens',
  },
  {
    id: 9,
    src: '/images/projects/chakvi-tropical-1.jpeg',
    category: 'kitchens',
  },
  {
    id: 10,
    src: '/images/projects/kobuleti.jpeg',
    category: 'kitchens',
  },
  {
    id: 11,
    src: '/images/projects/kobuleti-1.jpeg',
    category: 'kitchens',
  },
];
