import type { Project } from './types';

export const projects: Project[] = [
  {
    id: 1,
    src: '/images/projects/br_1/1.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 2,
    src: '/images/projects/br_1/2.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 3,
    src: '/images/projects/br_1/3.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 4,
    src: '/images/projects/br_1/4.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 5,
    src: '/images/projects/br_1/5.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 6,
    src: '/images/projects/br_1/6.jpg',
    category: 'projects',
    address: 'Bagrationi Residence - Studio',
  },
  {
    id: 7,
    src: '/images/projects/br_2/1.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 8,
    src: '/images/projects/br_2/2.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 9,
    src: '/images/projects/br_2/3.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 10,
    src: '/images/projects/br_2/4.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 11,
    src: '/images/projects/br_2/5.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 12,
    src: '/images/projects/br_2/6.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 13,
    src: '/images/projects/br_2/7.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 14,
    src: '/images/projects/br_2/8.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 15,
    src: '/images/projects/br_2/9.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 16,
    src: '/images/projects/br_2/10.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 17,
    src: '/images/projects/br_2/11.jpg',
    category: 'projects',
    address: 'Bagrationi Residence',
  },
  {
    id: 18,
    src: '/images/projects/pt/1.jpeg',
    category: 'projects',
    address: 'PortaTower',
  },
  {
    id: 19,
    src: '/images/projects/pt/2.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 20,
    src: '/images/projects/pt/3.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 21,
    src: '/images/projects/pt/4.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 22,
    src: '/images/projects/pt/5.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 23,
    src: '/images/projects/pt/6.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 24,
    src: '/images/projects/pt/7.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 25,
    src: '/images/projects/pt/8.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 26,
    src: '/images/projects/pt/9.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 27,
    src: '/images/projects/pt/10.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 28,
    src: '/images/projects/pt/11.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 29,
    src: '/images/projects/pt/12.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 30,
    src: '/images/projects/pt/13.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 31,
    src: '/images/projects/pt/14.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 32,
    src: '/images/projects/pt/15.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 33,
    src: '/images/projects/pt/16.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 34,
    src: '/images/projects/pt/17.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 35,
    src: '/images/projects/pt/18.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 36,
    src: '/images/projects/pt/19.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 37,
    src: '/images/projects/pt/20.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 38,
    src: '/images/projects/pt/21.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 39,
    src: '/images/projects/pt/22.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 40,
    src: '/images/projects/pt/23.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 41,
    src: '/images/projects/pt/24.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 42,
    src: '/images/projects/pt/25.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 43,
    src: '/images/projects/pt/26.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 44,
    src: '/images/projects/pt/27.jpeg',
    category: 'projects',
    address: 'Porta Tower',
  },
  {
    id: 45,
    src: '/images/projects/5.jpeg',
    category: 'wardrobes',
  },
  {
    id: 46,
    src: '/images/projects/6.jpg',
    category: 'kitchens',
  },
  {
    id: 47,
    src: '/images/projects/7.jpg',
    category: 'kitchens',
  },
  {
    id: 48,
    src: '/images/projects/8.jpeg',
    category: 'kitchens',
  },
  {
    id: 49,
    src: '/images/projects/10.jpeg',
    category: 'b2b',
  },
  {
    id: 50,
    src: '/images/projects/11.jpeg',
    category: 'wardrobes',
  },
  {
    id: 51,
    src: '/images/projects/12.jpeg',
    category: 'kitchens',
  },
  {
    id: 52,
    src: '/images/projects/13.jpeg',
    category: 'hallways',
  },
  {
    id: 53,
    src: '/images/projects/chakvi-tropical.jpeg',
    category: 'kitchens',
  },
  {
    id: 54,
    src: '/images/projects/chakvi-tropical-1.jpeg',
    category: 'kitchens',
  },
  {
    id: 55,
    src: '/images/projects/kobuleti.jpeg',
    category: 'kitchens',
  },
  {
    id: 56,
    src: '/images/projects/kobuleti-1.jpeg',
    category: 'kitchens',
  },
];
